[cursor]
blink_interval = 200

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14.3

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Bold"

[scrolling]
history = 50000

[window]
opacity = 1
startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true





## Normal color code

#[colors]
#[colors.primary]
#foreground = "#d8d8d8"
#background = "#272626"




# ## ashes.dark color code
# 
# [colors.primary]
# background = "#1c2023"
# foreground = "#c7ccd1"
# [colors.normal]
# black = "#1c2023"
# red = "#c7ae95"
# green = "#95c7ae"
# yellow = "#aec795"
# blue = "#ae95c7"
# magenta = "#c795ae"
# cyan = "#95aec7"
# white = "#c7ccd1"
# [colors.bright]
# black = "#747c84"
# red = "#c7ae95"
# green = "#95c7ae"
# yellow = "#aec795"
# blue = "#ae95c7"
# magenta = "#c795ae"
# cyan = "#95aec7"
# white = "#f3f4f5"




#  ## codeschool.dark
#  
#  [colors.primary]
#  background = "#232c31"
#  foreground = "#9ea7a6"
#  [colors.normal]
#  black = "#232c31"
#  red = "#2a5491"
#  green = "#237986"
#  yellow = "#a03b1e"
#  blue = "#9072c6"
#  magenta = "#c59820"
#  cyan = "#b02f30"
#  white = "#9ea7a6"
#  [colors.bright]
#  black = "#3f4944"
#  red = "#2a5491"
#  green = "#237986"
#  yellow = "#a03b1e"
#  blue = "#484d79"
#  magenta = "#c59820"
#  cyan = "#b02f30"
#  white = "#b5d8f6"



### embers dark 
#
#[colors.primary]
#background = "#16130f"
#foreground = "#a39a90"
#[colors.normal]
#black = "#16130f"
#red = "#826d57"
#green = "#57826d"
#yellow = "#6d8257"
#blue = "#6d5782"
#magenta = "#82576d"
#cyan = "#576d82"
#white = "#a39a90"
#[colors.bright]
#black = "#5a5047"
#red = "#826d57"
#green = "#57826d"
#yellow = "#6d8257"
#blue = "#6d5782"
#magenta = "#82576d"
#cyan = "#576d82"
#white = "#dbd6d1"



### isotope dark
#
#[colors.primary]
#background = "#000000"
#foreground = "#d0d0d0"
#[colors.normal]
#black = "#000000"
#red = "#ff0000"
#green = "#33ff00"
#yellow = "#ff0099"
#blue = "#0066ff"
#magenta = "#cc00ff"
#cyan = "#00ffff"
#white = "#d0d0d0"
#[colors.bright]
#black = "#808080"
#red = "#ff0000"
#green = "#33ff00"
#yellow = "#ff0099"
#blue = "#0066ff"
#magenta = "#cc00ff"
#cyan = "#00ffff"
#white = "#ffffff"




### Shape Shifter dark
#
#[colors.primary]
#background = "#000000"
#foreground = "#ababab"
#[colors.normal]
#black = "#000000"
#red = "#e92f2f"
#green = "#0ed839"
#yellow = "#dddd13"
#blue = "#3b48e3"
#magenta = "#f996e2"
#cyan = "#23edda"
#white = "#ababab"
#[colors.bright]
#black = "#343434"
#red = "#e92f2f"
#green = "#0ed839"
#yellow = "#dddd13"
#blue = "#3b48e3"
#magenta = "#f996e2"
#cyan = "#23edda"
#white = "#f9f9f9" 





### Catppuccin Mocha
#
#[colors.primary]
#background = "#1e1e2e"
#foreground = "#cdd6f4"
#dim_foreground = "#7f849c"
#bright_foreground = "#cdd6f4"
#[colors.cursor]
#text = "#1e1e2e"
#cursor = "#f5e0dc"
#[colors.vi_mode_cursor]
#text = "#1e1e2e"
#cursor = "#b4befe"
#[colors.search.matches]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#[colors.search.focused_match]
#foreground = "#1e1e2e"
#background = "#a6e3a1"
#[colors.footer_bar]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#[colors.hints.start]
#foreground = "#1e1e2e"
#background = "#f9e2af"
#[colors.hints.end]
#foreground = "#1e1e2e"
#background = "#a6adc8"
#[colors.selection]
#text = "#1e1e2e"
#background = "#f5e0dc"
#[colors.normal]
#black = "#45475a"
#red = "#f38ba8"
#green = "#a6e3a1"
#yellow = "#f9e2af"
#blue = "#89b4fa"
#magenta = "#f5c2e7"
#cyan = "#94e2d5"
#white = "#bac2de"
#[colors.bright]
#black = "#585b70"
#red = "#f38ba8"
#green = "#a6e3a1"
#yellow = "#f9e2af"
#blue = "#89b4fa"
#magenta = "#f5c2e7"
#cyan = "#94e2d5"
#white = "#a6adc8"
#[colors.dim]
#black = "#45475a"
#red = "#f38ba8"
#green = "#a6e3a1"
#yellow = "#f9e2af"
#blue = "#89b4fa"
#magenta = "#f5c2e7"
#cyan = "#94e2d5"
#white = "#bac2de"
#[[colors.indexed_colors]]
#index = 16
#color = "#fab387"
#[[colors.indexed_colors]]
#index = 17
#color = "#f5e0dc"




# Rosepine Theme for alacritty

[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"
[colors.cursor]
text = "#191724"
cursor = "#ff0000"
[colors.vi_mode_cursor]
text = "#191724"
cursor = "#eb6f92"
[colors.search.matches]
foreground = "#908caa"
background = "#26233a"
[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"
[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"
[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"
[colors.line_indicator]
foreground = "None"
background = "None"
[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"
[colors.selection]
text = "#e0def4"
background = "#403d52"
[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"



### Eldritch colorscheme
#
#[colors.primary]
#background = '#212337'
#foreground = '#ebfafa'
#[colors.cursor]
#cursor = '#37f499'
#text = '#f8f8f2'
#[colors.normal]
#black = '#21222c'
#blue = '#9071f4'
#cyan = '#04d1f9'
#green = '#37f499'
#magenta = '#f265b5'
#red = '#f9515d'
#white = '#ebfafa'
#yellow = '#e9f941'
#[colors.bright]
#black = '#7081d0'
#blue = '#a48cf2'
#cyan = '#66e4fd'
#green = '#69f8b3'
#magenta = '#fd92ce'
#red = '#f16c75'
#white = '#ffffff'
#yellow = '#f1fc79'
#[colors.selection]
#background = '#bf4f8e'
#text = '#ebfafa'
