[cursor]
blink_interval = 200

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 15

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 50000

[window]
opacity = 1
startup_mode = "Maximized"



## Normal color code

#[colors]
#[colors.primary]
#foreground = "#d8d8d8"
#background = "#272626"




# ## ashes.dark color code
# 
# [colors.primary]
# background = "#1c2023"
# foreground = "#c7ccd1"
# [colors.normal]
# black = "#1c2023"
# red = "#c7ae95"
# green = "#95c7ae"
# yellow = "#aec795"
# blue = "#ae95c7"
# magenta = "#c795ae"
# cyan = "#95aec7"
# white = "#c7ccd1"
# [colors.bright]
# black = "#747c84"
# red = "#c7ae95"
# green = "#95c7ae"
# yellow = "#aec795"
# blue = "#ae95c7"
# magenta = "#c795ae"
# cyan = "#95aec7"
# white = "#f3f4f5"




#  ## codeschool.dark
#  
#  [colors.primary]
#  background = "#232c31"
#  foreground = "#9ea7a6"
#  [colors.normal]
#  black = "#232c31"
#  red = "#2a5491"
#  green = "#237986"
#  yellow = "#a03b1e"
#  blue = "#9072c6"
#  magenta = "#c59820"
#  cyan = "#b02f30"
#  white = "#9ea7a6"
#  [colors.bright]
#  black = "#3f4944"
#  red = "#2a5491"
#  green = "#237986"
#  yellow = "#a03b1e"
#  blue = "#484d79"
#  magenta = "#c59820"
#  cyan = "#b02f30"
#  white = "#b5d8f6"
 


### embers dark 
#
#[colors.primary]
#background = "#16130f"
#foreground = "#a39a90"
#[colors.normal]
#black = "#16130f"
#red = "#826d57"
#green = "#57826d"
#yellow = "#6d8257"
#blue = "#6d5782"
#magenta = "#82576d"
#cyan = "#576d82"
#white = "#a39a90"
#[colors.bright]
#black = "#5a5047"
#red = "#826d57"
#green = "#57826d"
#yellow = "#6d8257"
#blue = "#6d5782"
#magenta = "#82576d"
#cyan = "#576d82"
#white = "#dbd6d1"



### isotope dark
#
#[colors.primary]
#background = "#000000"
#foreground = "#d0d0d0"
#[colors.normal]
#black = "#000000"
#red = "#ff0000"
#green = "#33ff00"
#yellow = "#ff0099"
#blue = "#0066ff"
#magenta = "#cc00ff"
#cyan = "#00ffff"
#white = "#d0d0d0"
#[colors.bright]
#black = "#808080"
#red = "#ff0000"
#green = "#33ff00"
#yellow = "#ff0099"
#blue = "#0066ff"
#magenta = "#cc00ff"
#cyan = "#00ffff"
#white = "#ffffff"




### Shape Shifter dark
#
#[colors.primary]
#background = "#000000"
#foreground = "#ababab"
#[colors.normal]
#black = "#000000"
#red = "#e92f2f"
#green = "#0ed839"
#yellow = "#dddd13"
#blue = "#3b48e3"
#magenta = "#f996e2"
#cyan = "#23edda"
#white = "#ababab"
#[colors.bright]
#black = "#343434"
#red = "#e92f2f"
#green = "#0ed839"
#yellow = "#dddd13"
#blue = "#3b48e3"
#magenta = "#f996e2"
#cyan = "#23edda"
#white = "#f9f9f9" 





## Catppuccin Mocha

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"
[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"
[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"
[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"
[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"
[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"
[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"
[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"
[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"
[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
[[colors.indexed_colors]]
index = 16
color = "#fab387"
[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"





### Cattpuccin Macchiato
#
#[colors.primary]
#background = "#24273a"
#foreground = "#cad3f5"
#dim_foreground = "#8087a2"
#bright_foreground = "#cad3f5"
#[colors.cursor]
#text = "#24273a"
#cursor = "#f4dbd6"
#[colors.vi_mode_cursor]
#text = "#24273a"
#cursor = "#b7bdf8"
#[colors.search.matches]
#foreground = "#24273a"
#background = "#a5adcb"
#[colors.search.focused_match]
#foreground = "#24273a"
#background = "#a6da95"
#[colors.footer_bar]
#foreground = "#24273a"
#background = "#a5adcb"
#[colors.hints.start]
#foreground = "#24273a"
#background = "#eed49f"
#[colors.hints.end]
#foreground = "#24273a"
#background = "#a5adcb"
#[colors.selection]
#text = "#24273a"
#background = "#f4dbd6"
#[colors.normal]
#black = "#494d64"
#red = "#ed8796"
#green = "#a6da95"
#yellow = "#eed49f"
#blue = "#8aadf4"
#magenta = "#f5bde6"
#cyan = "#8bd5ca"
#white = "#b8c0e0"
#[colors.bright]
#black = "#5b6078"
#red = "#ed8796"
#green = "#a6da95"
#yellow = "#eed49f"
#blue = "#8aadf4"
#magenta = "#f5bde6"
#cyan = "#8bd5ca"
#white = "#a5adcb"
#[colors.dim]
#black = "#494d64"
#red = "#ed8796"
#green = "#a6da95"
#yellow = "#eed49f"
#blue = "#8aadf4"
#magenta = "#f5bde6"
#cyan = "#8bd5ca"
#white = "#b8c0e0"
#[[colors.indexed_colors]]
#index = 16
#color = "#f5a97f"
#[[colors.indexed_colors]]
#index = 17
#color = "#f4dbd6"
