#### GPU Acceleration


## ==== Functional ====
vo=gpu-next # gpu,gpu-next
hwdec=auto
hwdec-codecs=all
gpu-api=vulkan # vulkan,opengl
profile=fast
fbo-format=rgba32f



### ==== Performance ====
deinterlace=auto # auto,yes,no
hdr-compute-peak=yes # auto,yes,no
# interpolation=yes # no,yes
# video-sync=display-resample
# dscale=bilinear,mitchell
# scale=bilinear
# vd-lavc-dr=yes
# vulkan-async-compute=yes
# vulkan-async-transfer=yes
# opengl-pbo=yes
# vd=h264_qsv,hevc_qsv,vc1_qsv,vp9_qsv
# scale=lanczos
# cscale=lanczos
# correct-downscaling=yes
# linear-downscaling=yes
# linear-upscaling=no
# sigmoid-upscaling=yes
# deband=yes
# allow-delayed-peak-detect=yes
# vulkan-async-compute=yes
# vulkan-async-transfer=yes
# vulkan-queue-count=1
# vd-lavc-dr=yes
# display-fps-override=60
# tscale=oversample # smoothmotion


## ==== General ====

osd-font='Droid Sans'
osd-font-size=45
osd-scale=0.5
osd-on-seek=msg-bar
osd-playing-msg = "${filename}"
osd-duration=2000
osd-status-msg='${filename}\n \n   ${time-pos}/${duration} (${percent-pos}%)'
sub-font="SUSE Medium"
sub-ass-style-overrides=FontName="SUSE Medium",FontSize=35 # sometimes culprit
# sub-color='#55b4ff'
sub-color='#FF5555'
sub-font-size=33
sub-blur=0.2
sub-border-color='#000000'
sub-border-size=2
sub-shadow-offset=0
sub-auto=all
sub-pos=102
sub-justify=left
alang=eng,en,english
slang=en,eng, english
msg-color=yes # color log messages on terminal
term-osd-bar=yes # displays a progress bar on the terminal
cursor-autohide=1000 # autohides the cursor after 1s
demuxer-max-bytes=1GiB # Cache during Online Video playback
force-window # helps during video less video playback





# --- HDR to SDR Vibrancy Tweaks ---

[HDR-Vibrant]
profile-cond=p["video-params/gamma"] == "pq"
# profile-cond=p["video-params/gamma"] == "pq" or (p["video-params/pixelformat"] == "yuv420p10le" and p["video-params/hwdec-interop"] ~= "no")
profile-restore=copy
tone-mapping=mobius                # Generally looks punchier/brighter than others         
tone-mapping-param=0.3             # Adjusts the "knee" of the curve; lower = brighter
target-peak=250                    # Matches typical ThinkPad nits; lower = brighter image 
gamut-mapping-mode=perceptual      # Helps keep colors saturated but natural 
target-colorspace-hint=no          # Necessary for Linux SDR screens          
allow-delayed-peak-detect=yes      # Performance boost for your i3 CPU
# Optional: Extra "pop" for the ThinkPad screen
saturation=10
contrast=2


#NOTE: 
#1. VD= any of h264_qsv or any libmfx caused errors like video not playing but audio playing
#   this is solved by adding the HWDEC-CODECS=ALL option which fallbacks to software video
#   decoding if found any fault in the hardware decoding.
#
#
#
#
#
